config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  get '/users/:id', to: "users#show", as: "users_show"
  get '/songs', to: "songs#index", as: "songs_index"
  get '/search', to: "songs#search", as: "songs_search"
  get '/suggestions', to: "songs#suggestions", as: "songs_suggestions"
  post '/suggestions', to: "songs#create", as: "songs_create"
  #get '/vote', to: "users#playlist", as: "users_playlist"
  post '/vote', to: "users#vote", as: "vote"
  get '/index', to: "song_votes#index", as: "song_votes_index"
  # The priority is based upon order of , creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs through :song_votes
end

app/models/song.rb
class Song < ActiveRecord::Base
  # has_many :song_votes
  # has_many :playlists
  # has_many :users, through: :song_votes
  belongs_to :user
  belongs_to :playlists
  has_many :song_votes
end

app/models/song_vote.rb
class SongVote < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
  #belongs_to :playlist
end


def self.vote(song, user)
    vote = SongVote.new()
    vote.user_id = user.id
    vote.song_id = song.id
    vote.save
  end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :song_votes
  has_many :playlists
  has_many :songs, through: :song_votes






end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def create

  end

  def show

  end

  def index

  end



end

app/controllers/song_votes_controller.rb
class SongVotesController < ApplicationController

  def index
    @groups = SongVote.group('title').order('count_id desc').count('id')
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def show

  end

  def index

  end

  # def suggestions
  #   binding.pry
  #   @suggestions = Song.all
  #   #render :suggestion
  # end

  def search
    @results = []
    @title = params[:title]
    if @title
      @results = RSpotify::Track.search(@title)
    end
  end

  def create
    song = params[:song]
    spotify = song[:spotify_id]
      if Song.find_by spotify_id: spotify
        flash[:notice] = "Suggestion already added. Please select another."
        redirect_to songs_index_path
      else
        @suggest = Song.new(song_params)
        @suggest.save
        @suggestions = Song.all
        render :suggestions
      end

  end

  private
  def song_params
    params.require(:song).permit(:spotify_id, :user_id, :title, :artist, :album)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_song, only: [:vote]
  before_action :authenticate_user!


  def index
    @users = User.all
  end

  def show
    @user = current_user
    render :show
  end

  def vote
    if current_user.vote_count > 0
      @vote = SongVote.new(vote_params)
      @vote.save
      @user = User.find(current_user)
      total_votes = current_user.vote_count - 1
      @user.update(:vote_count => total_votes)
      render :vote
    else
      flash[:alert] = "You currently have no votes to use! Please check back at the start of the new week"
      render :show
    end
  end


private
  def vote_params
    params.require(:song_vote).permit(:song_id, :user_id, :artist, :title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spotifer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
         <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/song_votes/index.html.erb
<div class="header">
  <h2> Spotifer </h2>
  <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSBjCrgjQNC7aTn7FV4mxXVmxBITCv5RTp7JMI8a1RNFdGM4WEnLA" id="logo">
    <h1>Votes List</h1>
      <div class='top-buttons'>
        <%= link_to 'Back to Search', songs_index_path, class: "btn btn-default btn-sm" %>  <%= link_to 'Go to Your Profile Page', users_show_path(current_user), class: "btn btn-default btn-sm" %>
      </div>
</div>


<table class="table table-striped">
  <% @groups.each do |g| %>
  <tr>
      <td><%= g[0] %> </td>
    <%end%>
  </tr>
</table>

app/views/songs/index.html.erb
<div class="header">
  <h2> Spotifer </h2>
  <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSBjCrgjQNC7aTn7FV4mxXVmxBITCv5RTp7JMI8a1RNFdGM4WEnLA" id="logo">
    <h1> Search Page </h1>
      <div class='top-buttons'>
        <%= link_to 'Go to Your Profile Page', users_show_path(current_user), class: "btn btn-default btn-sm" %>
      </div>
</div>


  <div class="form-group form-inline searchWrap">  <div>
          <%= form_tag '/search', method: 'get' do %>
          <%= text_field_tag 'title',
                        params[:title],
                        :class => "form-control input-lg searchBox",
                        :placeholder => 'Search by Artist' %>
  </div>

  <div>
            <%= button_tag(type: "submit", class: "btn btn-primary btn-lg searchButton") do %>
              Search <i class="fa fa-sign-out"></i>
            <% end %>
          <% end %>
      </div>
  </div>

app/views/songs/search.html.erb
<div class="header">
  <h2> Spotifer </h2>
  <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSBjCrgjQNC7aTn7FV4mxXVmxBITCv5RTp7JMI8a1RNFdGM4WEnLA" id="logo">
    <h1>Results for <u><em><%= @title %></em></u></h1>
      <div class='top-buttons'>
        <%= link_to 'Back to Search', songs_index_path, class: "btn btn-default btn-sm" %>  <%= link_to 'Go to Your Profile Page', users_show_path(current_user), class: "btn btn-default btn-sm" %>
      </div>
</div>

<table class="table table-striped">
  <% @results.each do |r| %>
  <tr>
      <td><%= r.name %><div class="sugg-button"><%= button_to('Suggest',
                                                    songs_create_path(:song => {:user_id => current_user.id,
                                                      :spotify_id => r.id, :artist => r.artists.first.name,
                                                      :title => r.name, :album => r.album.name}),
       method: :post, class: "btn btn-default btn-sm") %></div></td>
    <% end %>
  </tr>
</table>

app/views/songs/show.html.erb
<div class="header">
  <h2> Spotifer </h2>
  <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSBjCrgjQNC7aTn7FV4mxXVmxBITCv5RTp7JMI8a1RNFdGM4WEnLA" id="logo">
    <h1>Results for <u><em><%= @title %></em></u></h1>
      <div class='top-buttons'>
        <%= link_to 'Back to Search', songs_index_path, class: "btn btn-default btn-sm" %>  <%= link_to 'Go to Your Profile Page', users_show_path(current_user), class: "btn btn-default btn-sm" %>
      </div>
</div>

<table class="table table-striped">
  <% @results.each do |r| %>
  <tr>
      <td><%= r.name %><%= button_to 'Suggest', songs_create_path,
        method: :post,
        params: [song: {
          spotify_id: r.id,
          user_id: current_user.id,
          title: r.name,
          artist: r.artists.first.name,
          album: r.album.name
          }
        ], class: "btn btn-default btn-sm" %></td>
    <% end %>
  </tr>
</table>

app/views/songs/suggestions.html.erb
<div class="header">
  <h2> Spotifer </h2>
  <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSBjCrgjQNC7aTn7FV4mxXVmxBITCv5RTp7JMI8a1RNFdGM4WEnLA" id="logo">
    <h1>Current Suggestions</h1>
      <div class='top-buttons'>
        <%= link_to 'Back to Search', songs_index_path, class: "btn btn-default btn-sm" %>  <%= link_to 'Go to Your Profile Page', users_show_path(current_user), class: "btn btn-default btn-sm" %>
      </div>
</div>

<table class="table table-striped">
  <% @suggestions.each do |s| %>
  <tr>
      <td><%= s.title %> &nbsp &nbsp <small><strong><%=s.artist%></strong></small><div class="voting"><%= button_to('Vote',
                                                      vote_path(:song_vote => {:song_id => s.id, :user_id => current_user.id, :title => s.title, :artist => s.artist}),
                                                      method: :post, class: "btn btn-default btn-sm") %></div></td>
    <% end %>
  </tr>
</table>

app/views/users/index.html.erb
<p class="notice"><%= notice %></p>

<div class="header">
  <h2> Spotifer </h2>
    <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSBjCrgjQNC7aTn7FV4mxXVmxBITCv5RTp7JMI8a1RNFdGM4WEnLA" id="logo">
    <h1> Playlist App </h1>
      <div class='top-buttons'>
        <%= link_to 'Go to Your Profile Page', users_show_path(current_user), class: "btn btn-default btn-sm" %>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm" %>
      </div>
</div>
  <div class="Intro" >
    <p><strong>Below is a list of all users registered for the Spotifer app:</strong> </p>
    <br>
  </div>
    <br>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm" %> | <%= link_to 'Go to Your Profile Page', users_show_path(current_user), class: "btn btn-default btn-sm" %>
  <br>
--------------------------------------------
  <br>

  <ul>
    <% @users.each do |u| %>
      <li><%= u.email %></li>
    <% end %>
  </ul>

app/views/users/show.html.erb
<p class="notice"><%= notice %></p>

<header>
  <div class="header">
    <h2> Spotifer </h2>
      <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSBjCrgjQNC7aTn7FV4mxXVmxBITCv5RTp7JMI8a1RNFdGM4WEnLA" id="logo">

      <h1> Profile Page </h1>
        <div class='top-buttons'>
          <%= link_to 'Search for Song', songs_index_path, class: "btn btn-default btn-sm" %> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm" %>
        </div>
  </div>
</header>
<br>

<div class="main-content"
<p><strong>Username</strong>: <%= current_user.email %> </p>
</div>

app/views/users/vote.html.erb
<div class="header">
  <h2> Spotifer </h2>
  <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSBjCrgjQNC7aTn7FV4mxXVmxBITCv5RTp7JMI8a1RNFdGM4WEnLA" id="logo">
    <h1>Your Submission</h1>
      <div class='top-buttons'>
        <%= link_to 'Back to Search', songs_index_path, class: "btn btn-default btn-sm" %>  <%= link_to 'Go to Your Profile Page', users_show_path(current_user), class: "btn btn-default btn-sm" %>
      </div>
</div>




<h4> Voted for:&nbsp&nbsp <em><%= @vote.title %></em> &nbsp <em><small><%= @vote.artist %></small></em> </h4>

<br>

<div class="list-button"> <%= link_to 'List of Votes', song_votes_index_path, class: "btn btn-success btn-lg" %> </div>